# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c873406b2cfcb1e9639eaf2c9f9b2f988211c5495510abe2ce9e9cab8ff915b31d73f18cc64eca7d6ab6a0b9eb86026e885afb2a6735dc4098188cd83faecb1d

test:
  secret_key_base: ed2547e7767d64291e6a94a52b80f36ce9aed6770092c3b06f056dc7be80267a33fc8085555460123d3d3a21ec629314dad49bb63c73cc21863b96d8e6036f97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
